### ISSUE TITLE
 Could not locate the bindings file

### ISSUE THREAD

**Issue by alagukaja** [curlconverter/curlconverter#522]

**Comment by alagukaja** [comment]
→ /Users/maris/personal/crul-converter/node_modules/deasync/build/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/build/Debug/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/build/Release/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/out/Debug/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/Debug/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/out/Release/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/Release/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/build/default/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/compiled/16.19.1/darwin/arm64/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/addon-build/release/install-root/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/addon-build/debug/install-root/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/addon-build/default/install-root/deasync.node
 → /Users/maris/personal/crul-converter/node_modules/deasync/lib/binding/node-v93-darwin-arm64/deasync.node
    at bindings (/Users/maris/personal/crul-converter/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/maris/personal/crul-converter/node_modules/deasync/index.js:30:31)
    at Module._compile (/Users/maris/personal/crul-converter/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (/Users/maris/personal/crul-converter/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/maris/personal/crul-converter/node_modules/parcel-bundler/src/utils/syncPromise.js:1:79)
    at Module._compile (/Users/maris/personal/crul-converter/node_modules/v8-compile-cache/v8-compile-cache.js:192:30) {



Node : 14

**Comment by verhovsky** [comment]
I have no clue what you're saying here. I don't know what version of curlconverter you're trying to use, how you're building it or how to reproduce this error so I'm going to close this. If you want to provide step-by-step instructions for me to also encounter this error I can try to help at least understand what's going on.
