### ISSUE TITLE
yargs.boolean is not a function

### ISSUE THREAD

**Issue by crazyweeds** [curlconverter/curlconverter#530]
web project with react + curlconverter:3.21.0

`import * as curlconverter from 'curlconverter';`

`const convert = () => {
        const code = curlconverter.toGo("curl https://www.google.com");
        console.log(code)
    }`

error:

`util.js:36 Uncaught TypeError: yargs.boolean is not a function
    at Object.parseCurlCommand (util.js:36:1)
    at Object.toGo (go.js:5:1)
    at convert (CURL.jsx:18:1)
    at onClick (CURL.jsx:47:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)`

**Comment by verhovsky** [comment]
Works on my machine:

```sh
$ cd /tmp
$ mkdir curlconverter-yargs
$ cd curlconverter-yargs/
$ npm init -y
Wrote to /private/tmp/curlconverter-yargs/package.json:

{
  "name": "curlconverter-yargs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


$ npm install curlconverter@3.21.0

added 89 packages, and audited 90 packages in 6s

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ echo 'import * as curlconverter from "curlconverter";' > main.js
$ echo >> main.js
$ echo 'const code = curlconverter.toGo("curl https://www.google.com"); console.log(code)' >> main.js 
$ vim package.json  # add "type": "module", for import statement to work
$ node main.js 
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
)

[...]
```

**Comment by crazyweeds** [comment]
Update to version 4.5,It,s work.
