### ISSUE TITLE
Vite: globalThis.configs is not iterable

### ISSUE THREAD

**Issue by Sun-ZhenXing** [curlconverter/curlconverter#695]
I'm using this library in Vue, but it seems that the `global` variable is always translated to `globalThis`.

```log
TypeError: globalThis.configs is not iterable
    at parseArgs (curlconverter.js:5439:28)
    at parse (curlconverter.js:7163:28)
    at toPythonWarn (curlconverter.js:12016:20)
    at Module.toPython (curlconverter.js:12021:10)
    at update (index.vue:45:34)
    at callWithErrorHandling (runtime-core.esm-bundler.js:199:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:206:17)
    at baseWatchOptions.call (runtime-core.esm-bundler.js:6119:47)
    at job (reactivity.esm-bundler.js:1835:18)
    at callWithErrorHandling (runtime-core.esm-bundler.js:199:33)
```

Ref:

```js
function parseArgs(args2, longOpts = curlLongOpts, shortenedLongOpts = curlLongOptsShortened, shortOpts = curlShortOpts, supportedOpts, warnings = []) {
  let config2 = {
    authtype: CURLAUTH_BASIC,
    proxyauthtype: CURLAUTH_BASIC
  };
  const global = { configs: [config2], warnings };
  // ...

  // got ERROR: globalThis.configs is not iterable
  for (const cfg of global.configs) {
    for (const [arg, values] of Object.entries(cfg)) {
      if (Array.isArray(values) && !canBeList.has(arg)) {
        cfg[arg] = values[values.length - 1];
      }
    }
  }
  return [global, seen];
}
```

Is there a solution, or is `global` not a good variable name?

Test code:

```vue
<script setup lang="ts">
import * as curlconverter from 'curlconverter'

const command = ref('')
const result = ref('')

function update() {
  try {
    result.value = curlconverter.toPython(command.value)
  } catch (e: any) {
    console.error(e)
    result.value = e.message
  }
}
</script>
```

**Comment by verhovsky** [comment]
I used `global` because that's what curl uses

https://github.com/curl/curl/blob/dff66196d0bc52b53a91f59d3972769412f9639b/src/tool_getparam.c#L2680

but I knew it was a bad idea.
